version: "3"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=findata
      - POSTGRES_USER=finuser
      - POSTGRES_PASSWORD=finpass
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
